### ISSUE TITLE
"go get" not working on Linux Fedora, but install.sh does the job

### ISSUE THREAD

**Issue by mysticaltech** [MontFerret/cli#6]
Hello, just to signal that somehow both `go get` or `go get -u` are not working to install to GOPATH as other tools, the output is blank and `ferret` is not present.

However git cloning the repot, and doing `sudo ./install.sh` works well, so that issue is just FYI.

**Comment by 3timeslazy** [comment]
@mysticaltech hi!

Could you send me the command used to install the cli please?
If you trying to install ferret with `go` then use `go install github.com/MontFerret/cli/ferret@latest`

**Comment by mysticaltech** [comment]
That worked like a charm! Thanks, @3timeslazy! Was using `go get github.com/MontFerret/cli` and `go get -u github.com/MontFerret/cli` like in the readme.
